spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:f1v3;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


f1v3:
  hello:
    name: "seungjo"
    home: "hwasun"
    hobby: "programming"
    age: 26