### 게시글 작성

POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "제목입니다.",
  "content": "내용입니다."
}

### 인증 테스트 - 인증 실패

GET http://localhost:8080/f1v3
Content-Type: application/json

### 인증 테스트 - 인증 완료 (header)

GET http://localhost:8080/f1v3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzE1OTMwMTE5fQ.l4n9z835SiR8FONu306X7g4h6lW1uOxEzo02caCiq