### 인증 테스트 - 인증 실패

GET http://localhost:8080/f1v3
Content-Type: application/json

### 인증 테스트 - 인증 완료 (header)

GET http://localhost:8080/f1v3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzE1OTMwMTE5fQ.l4n9z835SiR8FONu306X7g4h6lW1uOxEzo02caCiq